// =====================================================
// DASHBOARD
// =====================================================
function renderMemberDashboardLists(){const a=document.getElementById('aktivitasList');if(a)a.innerHTML=['Mengikuti event Webinar Kewirausahaan Digital','Memberi komentar di forum #KompetisiCoding','Mengunggah foto ke Galeri Jawa Barat','Bergabung dengan cabang Bandung'].map(x=>`<div class="post-card">✓ ${x}</div>`).join('');const e=document.getElementById('myEventList');if(e)e.innerHTML=EVENTS.slice(0,3).map(x=>eventCardHtml(x)).join('');const p=document.getElementById('myPostList');if(p)p.innerHTML=POSTS.slice(0,3).map(x=>`<div class="post-card">${formatPostText(x.text)}<div class="post-actions">❤ ${x.likes}</div></div>`).join('');const n=document.getElementById('myNotifList');if(n)n.innerHTML='<div class="post-card">Tidak ada notifikasi baru.</div>';const pr=document.getElementById('myPrestasiList');if(pr)pr.innerHTML=ACHIEVEMENTS.map(x=>`<div class="col-md-4"><div class="card-nc"><b>${x.title}</b></div></div>`).join('');}
function renderAdminTables(){const sa=document.getElementById('admStatAnggota');const se=document.getElementById('admStatEvent');const sp=document.getElementById('admStatPost');if(sa)sa.textContent=MEMBERS.length*130+' +';if(se)se.textContent=EVENTS.filter(e=>!e.done).length;if(sp)sp.textContent=POSTS.length*46;const rows=(id,html)=>{const el=document.getElementById(id);if(el)el.innerHTML=html;};rows('admMemberTable',MEMBERS.map(m=>`<tr><td>${m.id}</td><td>${m.name}</td><td>${m.prov}</td><td>Aktif</td><td><button class="mini-btn" onclick="adminNotify('Data diperbarui')">✎</button></td></tr>`).join(''));rows('admPengurusTable',[['Ahmad Fauzan','Ketua Umum'],['Larasati Putri','Wakil Ketua'],['Bimo Nugroho','Sekretaris'],['Sari Wulandari','Bendahara']].map(p=>`<tr><td>${p[0]}</td><td>${p[1]}</td><td>Pusat</td><td>✓</td></tr>`).join(''));rows('admWilayahTable',PROVINCES.map(p=>`<tr><td>${p.n}</td><td>${p.members.toLocaleString('id-ID')}</td><td>${p.cabang}</td><td>${p.koor}</td><td><button class="mini-btn" onclick="flyToProvince('${p.n}')">Map</button></td></tr>`).join(''));rows('admForumTable',POSTS.map(p=>`<tr><td>${p.text}</td><td>${p.author}</td><td>${p.cat}</td><td>${p.likes}</td><td>—</td></tr>`).join(''));rows('admBeritaTable',NEWS.map(n=>`<tr><td>${n.title}</td><td>${n.cat}</td><td>${newsViewState[n.id]||n.views}</td><td>✎</td></tr>`).join(''));rows('admEventTable',EVENTS.map(e=>`<tr><td>${e.title}</td><td>${fmtDate(e.date)}</td><td>${e.peserta}/${e.kuota}</td><td>✎</td></tr>`).join(''));rows('admGaleriTable',GALLERY.map(g=>`<tr><td>${g.cap}</td><td>${g.type}</td><td>${g.daerah}</td><td>—</td></tr>`).join(''));rows('admDokumenTable',DOCS.map(d=>`<tr><td>${d.name}</td><td>${d.cat}</td><td>✎</td></tr>`).join(''));}
function adminNotify(msg){Swal.fire({icon:'success',title:msg,timer:1000,showConfirmButton:false});}
function adminConfirmDelete(what){Swal.fire({icon:'warning',title:'Yakin hapus?',text:`Data ${what} akan dihapus (demo).`,showCancelButton:true,confirmButtonText:'Hapus',confirmButtonColor:'#C1272D'});}
function exportLaporan(){Swal.fire({icon:'success',title:'Laporan sedang diekspor',text:'Ini masih simulasi.',confirmButtonColor:'#152A52'});}
function renderMemberChart(){if(!window.Chart)return;const c=document.getElementById('chartMemberActivity');if(c)new Chart(c,{type:'line',data:{labels:['Feb','Mar','Apr','Mei','Jun','Jul','Ags'],datasets:[{data:[4,7,5,9,12,8,14],borderColor:'#C1272D',backgroundColor:'rgba(193,39,45,.12)',fill:true,tension:.4}]},options:{plugins:{legend:{display:false}}}});}
function renderAdminCharts(){if(!window.Chart)return;new Chart(document.getElementById('chartAdminTren'),{type:'bar',data:{labels:['Feb','Mar','Apr','Mei','Jun','Jul','Ags'],datasets:[{label:'Anggota Baru',data:[120,180,150,210,260,300,280],backgroundColor:'#152A52'},{label:'Postingan Forum',data:[80,95,110,130,150,175,190],backgroundColor:'#C7972A'}]},options:{plugins:{legend:{position:'bottom'}}}});new Chart(document.getElementById('chartAdminKategori'),{type:'pie',data:{labels:['Umum','Teknologi','Event','Prestasi','Wilayah'],datasets:[{data:[30,25,20,15,10],backgroundColor:['#152A52','#C1272D','#C7972A','#1E8E5A','#24406F']}]},options:{plugins:{legend:{position:'bottom'}}}});}
