// =====================================================
// FORUM
// =====================================================
const FORUM_CATS=['Semua','Umum','Teknologi','Event','Prestasi','Wilayah'];let activeForumCat='Semua';
function renderForumChips(){document.getElementById('forumCatChips').innerHTML=FORUM_CATS.map(c=>`<button class="chip-btn ${c===activeForumCat?'active':''}" onclick="setForumCat('${c}')">${c}</button>`).join('');}
function setForumCat(c){activeForumCat=c;renderForumChips();renderForum();}
function formatPostText(t){return t.replace(/@([A-Za-z]+)/g,'<span class="mention">@$1</span>').replace(/#([A-Za-z0-9]+)/g,'<span class="hashtag">#$1</span>');}
function renderForum(){const q=(document.getElementById('forumSearch')?.value||'').toLowerCase();const list=POSTS.filter(p=>(activeForumCat==='Semua'||p.cat===activeForumCat)&&(p.text.toLowerCase().includes(q)||p.author.toLowerCase().includes(q)));document.getElementById('forumFeed').innerHTML=list.map(p=>`<div class="post-card"><div class="post-head"><img src="${p.avatar}"><div><b>${p.author}</b> <span class="tag-pill blue">${p.cat}</span><div class="meta">${p.prov} · ${p.time}</div></div></div><div class="post-body">${formatPostText(p.text)}</div>${p.poll?renderPoll(p):''}<div class="post-actions"><span onclick="toggleLike(${p.id})">❤ <span class="likeCount">${p.likes}</span></span><span onclick="toggleComment(${p.id})">💬 ${p.comments.length} Komentar</span><span onclick="toggleBookmarkPost(${p.id})">🔖 ${p.bookmark?'Tersimpan':'Simpan'}</span></div><div class="comment-box" id="comments-${p.id}">${p.comments.map(c=>`<div class="comment-item"><b>${c.a}:</b> ${c.t}</div>`).join('')}<div style="display:flex;gap:8px;margin-top:8px"><input id="cinput-${p.id}" placeholder="Tulis komentar…" style="flex:1;padding:8px"><button class="mini-btn" onclick="addComment(${p.id})">Kirim</button></div></div></div>`).join('')||'<p class="section-sub">Belum ada postingan.</p>';}
function renderPoll(p){const total=p.poll.options.reduce((a,o)=>a+o.v,0)||1;return `<div style="margin-bottom:10px">${p.poll.options.map((o,i)=>{const pct=Math.round(o.v/total*100);return `<div class="poll-opt" onclick="votePoll(${p.id},${i})"><div class="poll-fill" style="width:${p.poll.voted?pct:0}%"></div><span>${o.t} ${p.poll.voted?`<b>${pct}%</b>`:''}</span></div>`}).join('')}</div>`;}
function votePoll(id,i){const p=POSTS.find(x=>x.id===id);if(!p.poll.voted){p.poll.options[i].v++;p.poll.voted=true;renderForum();}}
function toggleLike(id){const p=POSTS.find(x=>x.id===id);p.liked=!p.liked;p.likes+=p.liked?1:-1;renderForum();}
function toggleBookmarkPost(id){const p=POSTS.find(x=>x.id===id);p.bookmark=!p.bookmark;renderForum();}
function toggleComment(id){document.getElementById('comments-'+id)?.classList.toggle('show');}
function addComment(id){const input=document.getElementById('cinput-'+id);if(!input?.value.trim())return;const p=POSTS.find(x=>x.id===id);p.comments.push({a:currentUser?currentUser.name:'Tamu',t:input.value.trim()});renderForum();document.getElementById('comments-'+id)?.classList.add('show');}
function submitPost(){requireLogin(()=>{const text=document.getElementById('newPostText').value.trim();if(!text){Swal.fire({icon:'warning',title:'Tulis sesuatu dulu ya',timer:1100,showConfirmButton:false});return;}POSTS.unshift({id:Date.now(),author:currentUser.name,prov:currentUser.prov,avatar:avatar(currentUser.name),time:'baru saja',cat:document.getElementById('newPostCat').value,text,likes:0,liked:false,bookmark:false,comments:[],poll:null});document.getElementById('newPostText').value='';renderForum();Swal.fire({icon:'success',title:'Postingan dipublikasikan',timer:1000,showConfirmButton:false});});}
