const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const STORAGE="nexora_event_v1";
let state=JSON.parse(localStorage.getItem(STORAGE)||'{"participants":[],"feedback":[],"theme":"dark","checkins":[],"payment":null}');
const save=()=>localStorage.setItem(STORAGE,JSON.stringify(state));
const toast=(msg,type="ok")=>{const t=$("#toast");t.textContent=msg;t.className="show "+type;clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.className="",2800)};
function ticketId(){return "NX-2026-"+Math.random().toString(36).slice(2,6).toUpperCase();}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function renderSpeakers(){const g=$("#speakerGrid");g.innerHTML=EVENT_DATA.speakers.map((s,i)=>`<article class="speaker reveal"><div class="speaker-photo"><div class="avatar">${s.initials}</div></div><div class="speaker-info"><h3>${s.name}</h3><small>${s.role}</small><p>${s.bio}</p><span class="topic">${s.topic}</span></div></article>`).join("");observe();}
function renderSchedule(){const q=$("#scheduleSearch").value.toLowerCase(),f=$("#scheduleFilter").value;const data=EVENT_DATA.schedule.filter(x=>(f==="all"||x.type===f)&&[x.title,x.speaker,x.room].join(" ").toLowerCase().includes(q));$("#scheduleList").innerHTML=data.map(x=>`<div class="schedule-item"><div class="time">${x.time}</div><div class="schedule-title">${x.title}</div><div class="schedule-speaker">${x.speaker}</div><div class="schedule-room">${x.room}</div></div>`).join("")||'<div class="panel">Tidak ada sesi yang cocok.</div>';}
function countdown(){const end=new Date(EVENT_DATA.date).getTime();const tick=()=>{let d=Math.max(0,end-Date.now()),s=Math.floor(d/1000);let days=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);s%=60;$("#days").textContent=String(days).padStart(2,"0");$("#hours").textContent=String(h).padStart(2,"0");$("#minutes").textContent=String(m).padStart(2,"0");$("#seconds").textContent=String(s).padStart(2,"0")};tick();setInterval(tick,1000)}
function showTicket(p){$("#digitalTicket").hidden=false;$("#ticketCard").innerHTML=`<div class="ticket-top"><b>NEXORA / 2026</b><span>GENERAL EVENT PASS</span></div><div class="ticket-main"><div><small>ATTENDEE</small><div class="ticket-name">${escapeHtml(p.name)}</div><p>${escapeHtml(p.institution)} · ${escapeHtml(p.ticket)}</p><br><small>PARTICIPANT ID</small><b>${p.id}</b><p>${EVENT_DATA.venue}</p></div><div><div class="qr" title="${p.id}"></div><small>SCAN AT CHECK-IN</small></div></div>`;$("#payment").hidden=!p.ticket.includes("Gratis");$("#checkin").hidden=false;$("#certificate").scrollIntoView({behavior:"smooth",block:"start"});localStorage.setItem("lastParticipant",p.id);}
function renderAdmin(page=1){const q=$("#participantSearch").value.toLowerCase();let arr=state.participants.filter(p=>[p.name,p.email,p.institution,p.id].join(" ").toLowerCase().includes(q));let size=6,pages=Math.max(1,Math.ceil(arr.length/size));page=Math.min(page,pages);let slice=arr.slice((page-1)*size,page*size);$("#participantTable").innerHTML=slice.map(p=>`<tr><td><b>${escapeHtml(p.name)}</b><br><small>${p.id}</small></td><td>${escapeHtml(p.institution)}</td><td>${escapeHtml(p.ticket.split(" — ")[0])}</td><td><span class="status ${p.status==="Pending"?"pending":""}">${p.status}</span></td><td><button class="action-delete" data-del="${p.id}">Hapus</button></td></tr>`).join("")||'<tr><td colspan="5">Belum ada peserta.</td></tr>';$("#pagination").innerHTML=Array.from({length:pages},(_,i)=>`<button class="page ${i+1===page?"active":""}" data-page="${i+1}">${i+1}</button>`).join("");$("#statParticipants").textContent=state.participants.length;$("#statCheckin").textContent=state.checkins.length;let ratings=state.feedback.map(x=>x.rating).filter(Boolean);$("#statRating").textContent=ratings.length?(ratings.reduce((a,b)=>a+b,0)/ratings.length).toFixed(1):"—";let rev=state.participants.reduce((n,p)=>n+(p.ticket.includes("VIP")?150000:p.ticket.includes("Workshop")?250000:0),0);$("#statRevenue").textContent="Rp"+rev.toLocaleString("id-ID");}
function observe(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.08});$$(".reveal:not(.visible)").forEach(e=>io.observe(e));}
$("#themeBtn").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";document.body.classList.toggle("light",state.theme==="light");$("#themeBtn").textContent=state.theme==="dark"?"🌙":"☀️";save()};
$("#menuBtn").onclick=()=>{$("#nav").style.display=$("#nav").style.display==="flex"?"":"flex";$("#nav").style.position="absolute";$("#nav").style.top="78px";$("#nav").style.right="5vw";$("#nav").style.flexDirection="column";$("#nav").style.padding="18px";$("#nav").style.background="#111319";$("#nav").style.border="1px solid #292c35";$("#nav").style.borderRadius="15px"};
$("#registerForm").onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));let p={...d,id:ticketId(),status:"Pending",created:new Date().toISOString()};state.participants.push(p);save();e.target.reset();showTicket(p);renderAdmin();toast("Pendaftaran berhasil! Tiket digital dibuat.");};
$$(".method").forEach(b=>b.onclick=()=>{$$(".method").forEach(x=>x.classList.remove("active"));b.classList.add("active")});
$("#paymentForm").onsubmit=e=>{e.preventDefault();let f=$("#proof").files[0];if(!f)return;state.payment={method:document.querySelector(".method.active").dataset.method,file:f.name,status:"Menunggu verifikasi"};save();$("#paymentStatus").textContent=`✓ ${f.name} berhasil disimpan sebagai bukti ${state.payment.method}. Status: Menunggu verifikasi.`;toast("Bukti pembayaran tersimpan.")};
let rating=0;$$(".stars button").forEach(b=>b.onclick=()=>{rating=+b.dataset.star;$$(".stars button").forEach(x=>x.classList.toggle("active",+x.dataset.star<=rating))});
$("#feedbackForm").onsubmit=e=>{e.preventDefault();if(!rating){toast("Pilih rating dulu.","error");return}state.feedback.push({rating,text:new FormData(e.target).get("feedback"),date:new Date().toISOString()});save();e.target.reset();rating=0;$$(".stars button").forEach(x=>x.classList.remove("active"));renderAdmin();toast("Terima kasih atas feedback kamu!")};
$("#checkinBtn").onclick=()=>{let id=$("#checkinId").value.trim().toUpperCase();let p=state.participants.find(x=>x.id===id);if(!p){$("#checkinResult").textContent="✕ Peserta tidak ditemukan.";return}if(!state.checkins.includes(id))state.checkins.push(id);p.status="Checked-in";save();renderAdmin();$("#checkinResult").textContent=`✓ ${p.name} terverifikasi dan berhasil check-in.`;$("#certBtn").disabled=false;$("#certText").textContent="Kehadiran terverifikasi. Sertifikat siap dibuat.";toast("Check-in berhasil!")};
$("#certBtn").onclick=()=>{let id=localStorage.getItem("lastParticipant"),p=state.participants.find(x=>x.id===id);if(!p||!state.checkins.includes(id)){toast("Lakukan check-in terlebih dahulu.","error");return}let w=window.open("","_blank");w.document.write(`<html><head><title>Sertifikat NEXORA</title><style>body{font-family:Arial;text-align:center;padding:80px;background:#111;color:#fff}main{border:2px solid #fff;padding:70px}h1{font-size:55px}p{font-size:20px}</style></head><body><main><small>NEXORA FUTURE EVENT 2026</small><h1>Certificate</h1><p>Dengan bangga diberikan kepada</p><h2>${escapeHtml(p.name)}</h2><p>atas partisipasinya dalam NEXORA — Build the Future.</p><p>Participant ID: ${p.id}</p><br><small>18 NOVEMBER 2026 · JAKARTA</small></main><script>window.print()<\/script></body></html>`);w.document.close()};
$("#participantSearch").oninput=()=>renderAdmin();$("#scheduleSearch").oninput=renderSchedule;$("#scheduleFilter").onchange=renderSchedule;
$("#pagination").onclick=e=>{if(e.target.dataset.page)renderAdmin(+e.target.dataset.page)};
$("#participantTable").onclick=e=>{let id=e.target.dataset.del;if(id){state.participants=state.participants.filter(p=>p.id!==id);state.checkins=state.checkins.filter(x=>x!==id);save();renderAdmin();toast("Data peserta dihapus.")}};
$("#addDemo").onclick=()=>{state.participants.push({name:"Demo Participant",email:"demo@nexora.test",phone:"0800000000",institution:"NEXORA Community",ticket:"General Admission — Gratis",id:ticketId(),status:"Pending",created:new Date().toISOString()});save();renderAdmin();toast("Peserta demo ditambahkan.")};
$("#scrollRegister").onclick=()=>$("#register").scrollIntoView({behavior:"smooth"});$("#markAll").onclick=()=>{state.participants.forEach(p=>{p.status="Checked-in";if(!state.checkins.includes(p.id))state.checkins.push(p.id)});save();renderAdmin();toast("Semua peserta disimulasikan check-in.")};
$("#clearData").onclick=()=>{if(confirm("Reset semua data lokal?")){state.participants=[];state.feedback=[];state.checkins=[];state.payment=null;save();renderAdmin();toast("Data lokal direset.")}};
$("#exportCsv").onclick=()=>{let rows=[["ID","Nama","Email","No HP","Instansi","Tiket","Status"],...state.participants.map(p=>[p.id,p.name,p.email,p.phone,p.institution,p.ticket,p.status])];let csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="nexora-peserta.csv";a.click();toast("CSV berhasil diekspor.")};
document.body.classList.toggle("light",state.theme==="light");$("#themeBtn").textContent=state.theme==="dark"?"🌙":"☀️";renderSpeakers();renderSchedule();renderAdmin();countdown();observe();